from __future__ import annotations

from typing import Any, Protocol, Self, runtime_checkable
from markupsafe import Markup

from . import tags as t

fieldset: type[t.fieldset]
legend: type[t.legend]

@runtime_checkable
class InputProvider(Protocol):
    def get_value(self) -> str | tuple[int | str, Any] | bool | None: ...
    def get_options(self) -> list[tuple[str, Any]]: ...
    def is_required(self) -> bool: ...
    def get_name(self) -> str: ...

class CSSTheme:
    def form_row(self) -> str: ...
    def inline_input_wrapper(self) -> str: ...
    def form_div(self) -> str: ...
    def label_class(self, offset: int) -> str: ...
    def input_class(self, *, error: bool = False) -> str: ...
    def select_class(self, *, error: bool = False) -> str: ...
    def textarea_class(self, *, error: bool = False) -> str: ...
    def value_col(self, size: int) -> str: ...
    def check_wrapper(self) -> str: ...
    def check_input_class(self) -> str: ...
    def check_label_class(self) -> str: ...
    def check_group_label_class(self, offset: int) -> str: ...
    def check_group_value_col(self, size: int) -> str: ...
    def error_feedback(self, message: str) -> t.Tag | str: ...
    def info_text(self, text: str) -> t.Tag | str: ...
    def info_popup(self, url: str) -> t.Tag: ...
    def badge_checked(self, label: str) -> t.Tag: ...
    def badge_unchecked(self, label: str) -> t.Tag: ...
    def badge_selected(self, text: str) -> t.Tag: ...
    def popover_attrs(self, title: str, content: str) -> dict[str, str]: ...

class Bootstrap53Theme(CSSTheme): ...

def set_theme(theme: CSSTheme) -> None: ...
def get_theme() -> CSSTheme: ...

class HTMLForm(t.pairedtag):
    _newline: bool
    readonly: bool
    scriptlinks: list[str]
    jscode: list[str]
    pyscode: list[str]
    def __init__(
        self,
        *,
        action: str = "",
        method: str = "post",
        enctype: str = "application/x-www-form-urlencoded",
        _readonly: bool = False,
        _main_container: bool = True,
        **kwargs: Any,
    ) -> None: ...
    @property
    def _tag(self) -> str: ...

class InlineInput(t.div):
    def __init__(self, **kwargs: Any) -> None: ...

class BaseInput(t.Tag):
    _type: str
    label: str | None
    input_provider: InputProvider | None
    value: Any
    options: list[tuple[str, str]] | None
    update_dict: dict[str, Any] | None
    placeholder: str
    error: str
    info: str
    size: int
    offset: int
    extra_control: str
    readonly: bool | None
    input_style: str
    popover: str
    multiple: bool
    always_show_input: bool
    ignore_disabled: bool

    def __init__(
        self,
        *,
        input_provider: InputProvider | None = None,
        name: str | None = None,
        label: str | None = None,
        value: Any = None,
        options: list[tuple[str, str]] | None = None,
        update_dict: dict[str, Any] | None = None,
        placeholder: str = "",
        info: str = "",
        size: int = 3,
        offset: int = 2,
        extra_control: str = "",
        readonly: bool | None = None,
        multiple: bool = False,
        input_style: str = "",
        popover: str = "",
        error: str = "",
        always_show_input: bool = False,
        ignore_disabled: bool = False,
        override_theme: CSSTheme | None = None,
        **kwargs: Any,
    ) -> None: ...
    def get_value(
        self,
    ) -> str | tuple[int | str, str] | list[tuple[int | str, str]] | bool | None: ...
    def get_options(self) -> list[tuple[str, str]] | None: ...
    def is_readonly(self) -> bool: ...
    def opts(self, **kwargs: Any) -> Self: ...
    def _theme(self) -> CSSTheme: ...
    def render_label(self) -> t.Tag | str: ...
    def render_input(self, value: Any = None) -> t.Tag: ...
    def render_info(self) -> t.Tag | str: ...
    def _wrap_row(self, content: Markup) -> Markup: ...
    def r(self) -> Markup: ...

class TextInput(BaseInput): ...
class EmailInput(BaseInput): ...
class PasswordInput(BaseInput): ...

class HiddenInput(BaseInput):
    _type: str
    def r(self) -> Markup: ...

class CheckboxInput(BaseInput):
    _type: str
    def get_value(self) -> bool: ...
    def render_label(self) -> t.Tag | str: ...
    def _render_check(self) -> t.Tag | str: ...
    def render_input(self, value: Any = None) -> t.Tag: ...
    def r(self) -> Markup: ...

class CheckboxGroupInput(BaseInput):
    def render_label(self) -> t.Tag | str: ...
    def render_input(self, value: Any = None) -> t.Tag: ...

class RadioInput(BaseInput):
    _type: str
    def render_input(self, value: Any = None) -> t.Tag: ...

class SelectInput(BaseInput):
    def render_input(self, value: Any = None) -> t.Tag: ...

class TextAreaInput(BaseInput):
    def render_input(self, value: Any = None) -> t.Tag: ...

class FileInput(BaseInput):
    _type: str
    removal_flag: str | None
    def __init__(self, removal_flag: str | None = None, **kwargs: Any) -> None: ...
    def render_input(self, value: Any = None) -> t.Tag: ...
