from __future__ import annotations

from typing import Any, Protocol, Self, runtime_checkable

from . import tags as t

fieldset: type[t.fieldset]
legend: type[t.legend]

@runtime_checkable
class InputProvider(Protocol):
    def get_value(self) -> Any: ...
    def get_options(self) -> list[tuple[Any, Any]]: ...
    def is_required(self) -> bool: ...
    def get_name(self) -> str: ...

class CSSTheme:
    def form_row(self) -> str: ...
    def inline_input_wrapper(self) -> str: ...
    def form_div(self) -> str: ...
    def label_class(self, offset: int) -> str: ...
    def input_class(self, *, error: bool = False) -> str: ...
    def select_class(self, *, error: bool = False) -> str: ...
    def textarea_class(self, *, error: bool = False) -> str: ...
    def value_col(self, size: int) -> str: ...
    def check_wrapper(self) -> str: ...
    def check_input_class(self) -> str: ...
    def check_label_class(self) -> str: ...
    def check_group_label_class(self, offset: int) -> str: ...
    def check_group_value_col(self, size: int) -> str: ...
    def error_feedback(self, message: str) -> t.Tag | str: ...
    def info_text(self, text: str) -> t.Tag | str: ...
    def info_popup(self, url: str) -> t.Tag: ...
    def badge_checked(self, label: str) -> t.Tag: ...
    def badge_unchecked(self, label: str) -> t.Tag: ...
    def badge_selected(self, text: str) -> t.Tag: ...
    def popover_attrs(self, title: str, content: str) -> dict[str, str]: ...

class Bootstrap53Theme(CSSTheme): ...

def set_theme(theme: CSSTheme) -> None: ...
def get_theme() -> CSSTheme: ...

class BaseInput:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, arg: Any) -> Self: ...
    def opts(self, **kwargs: Any) -> Self: ...
    def r(self) -> str: ...
    def __html__(self) -> str: ...
    def __tag__(self) -> t.Tag: ...

class InlineInput(BaseInput): ...
class TextInput(BaseInput): ...
class EmailInput(BaseInput): ...
class PasswordInput(BaseInput): ...
class HiddenInput(BaseInput): ...
class CheckboxInput(BaseInput): ...
class CheckboxGroupInput(BaseInput): ...
class RadioInput(BaseInput): ...
class SelectInput(BaseInput): ...
class TextAreaInput(BaseInput): ...
class FileInput(BaseInput): ...
class HTMLForm(BaseInput): ...
