from __future__ import annotations

from typing import Any, Protocol, Self
from markupsafe import Markup

class _TagAdapter(Protocol):
    def __tag__(self) -> Tag: ...

literal: type[Markup]

class _SelfInstantiating(type):
    def __str__(cls) -> str: ...
    def __getitem__(cls, args: Any) -> Tag: ...
    def __iadd__(cls, other: Any) -> Tag: ...

class Tag(metaclass=_SelfInstantiating):
    _newline: bool
    _main_container: bool
    _inline: bool

    def __init__(
        self,
        *args: Any,
        id: str | None = None,
        name: str | None = None,
        class_: str | None = None,
        _enabled: bool = True,
        _main_container: bool = False,
        _register: bool = True,
        **kwargs: Any,
    ) -> None: ...

    id: str | None
    name: str | None
    class_: str | None
    container: Tag | None
    contents: list[Tag | str]
    elements: dict[str, Tag]
    attrs: dict[str, Any]
    _enabled: bool
    _register: bool

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def add(self, *elements: Tag | Markup | str | type[Tag] | _TagAdapter) -> Self: ...
    def __iadd__(self, element: Any) -> Self: ...
    def __getitem__(self, arg: Any) -> Self: ...
    def insert(
        self,
        index: int,
        *elements: Tag | Markup | str | type[Tag] | _TagAdapter,
    ) -> Self: ...
    def replace(
        self, *elements: Tag | Markup | str | type[Tag] | _TagAdapter
    ) -> Self: ...
    def nonreg_add(
        self,
        *elements: Tag | Markup | str | type[Tag] | _TagAdapter,
    ) -> Self: ...
    def get_container(self) -> Tag: ...
    def __contains__(self, identifier: str) -> bool: ...
    def register_element(self, element: Any) -> None: ...
    def unregister_element(self, identifier: str) -> None: ...
    def get_element(self, identifier: str) -> Tag: ...
    def remove_element(self, identifier: str) -> Self: ...
    def set_attributes(self, kwargs: dict[str, Any]) -> Self: ...
    def attributes(self, attrs_only: bool = False) -> str: ...
    def opts(self, **kwargs: Any) -> Self: ...
    @property
    def _tag(self) -> str: ...
    def r(self) -> Markup: ...
    def pretty(self, *, level: int = 0, indent: str = "  ") -> str: ...
    def __html__(self) -> Markup: ...

class fragment(Tag): ...

class singletag(Tag):
    _inline: bool
    def _reject_content(self) -> None: ...
    def add(self, *elements: Tag | Markup | str | type[Tag] | _TagAdapter) -> Self: ...
    def insert(
        self,
        index: int,
        *elements: Tag | Markup | str | type[Tag] | _TagAdapter,
    ) -> Self: ...
    def replace(
        self, *elements: Tag | Markup | str | type[Tag] | _TagAdapter
    ) -> Self: ...
    def nonreg_add(
        self,
        *elements: Tag | Markup | str | type[Tag] | _TagAdapter,
    ) -> Self: ...

class pairedtag(Tag): ...
class img(singletag): ...
class input(singletag): ...
class br(singletag): ...
class hr(singletag): ...
class meta(singletag): ...
class link(singletag): ...
class source(singletag): ...
class track(singletag): ...
class wbr(singletag): ...
class param(singletag): ...
class col(singletag): ...
class embed(singletag): ...
class area(singletag): ...
class base(singletag): ...
class div(pairedtag): ...
class span(pairedtag): ...
class p(pairedtag): ...
class a(pairedtag): ...
class b(pairedtag): ...
class i(pairedtag): ...
class table(pairedtag): ...
class thead(pairedtag): ...
class tbody(pairedtag): ...
class tr(pairedtag): ...
class td(pairedtag): ...
class th(pairedtag): ...
class form(pairedtag): ...
class label(pairedtag): ...
class button(pairedtag): ...
class textarea(pairedtag): ...
class select(pairedtag): ...
class option(pairedtag): ...
class h1(pairedtag): ...
class h2(pairedtag): ...
class h3(pairedtag): ...
class h4(pairedtag): ...
class h5(pairedtag): ...
class h6(pairedtag): ...
class nav(pairedtag): ...
class footer(pairedtag): ...
class header(pairedtag): ...
class section(pairedtag): ...
class article(pairedtag): ...
class aside(pairedtag): ...
class dl(pairedtag): ...
class dt(pairedtag): ...
class dd(pairedtag): ...
class fieldset(pairedtag): ...
class legend(pairedtag): ...
class pre(pairedtag): ...
class code(pairedtag): ...
class blockquote(pairedtag): ...
class html(pairedtag): ...
class head(pairedtag): ...
class body(pairedtag): ...
class time(pairedtag): ...
class strong(pairedtag): ...
class small(pairedtag): ...
class template(pairedtag): ...
class li(pairedtag): ...

class ul(pairedtag):
    def add(self, *args: Tag | Markup | str) -> Self: ...

class ol(ul): ...
