from __future__ import annotations

from typing import Any, Self

literal: Any

class _SelfInstantiating(type):
    def __getitem__(cls, args: Any) -> Tag: ...
    def __iadd__(cls, other: Any) -> Tag: ...

class Tag(metaclass=_SelfInstantiating):
    def __init__(
        self,
        *args: Any,
        **kwargs: Any,
    ) -> None: ...
    def add(self, *elements: Tag | str | type[Tag]) -> Self: ...
    def __iadd__(self, element: Any) -> Self: ...
    def __getitem__(self, arg: Any) -> Self: ...
    def insert(self, index: int, *elements: Tag | str) -> Self: ...
    def replace(self, *elements: Tag | str) -> Self: ...
    def nonreg_add(self, *elements: Tag | str) -> Self: ...
    def set_attributes(self, kwargs: dict[str, Any]) -> Self: ...
    def attributes(self, attrs_only: bool = False) -> str: ...
    def opts(self, **kwargs: Any) -> Self: ...
    def r(self) -> str: ...
    def pretty(self, *, level: int = 0, indent: str = "  ") -> str: ...
    def __html__(self) -> str: ...

class fragment(Tag): ...
class singletag(Tag): ...
class pairedtag(Tag): ...
class img(singletag): ...
class input(singletag): ...
class br(singletag): ...
class hr(singletag): ...
class meta(singletag): ...
class link(singletag): ...
class source(singletag): ...
class track(singletag): ...
class wbr(singletag): ...
class param(singletag): ...
class col(singletag): ...
class embed(singletag): ...
class area(singletag): ...
class base(singletag): ...
class div(pairedtag): ...
class span(pairedtag): ...
class p(pairedtag): ...
class a(pairedtag): ...
class b(pairedtag): ...
class i(pairedtag): ...
class table(pairedtag): ...
class thead(pairedtag): ...
class tbody(pairedtag): ...
class tr(pairedtag): ...
class td(pairedtag): ...
class th(pairedtag): ...
class form(pairedtag): ...
class label(pairedtag): ...
class button(pairedtag): ...
class textarea(pairedtag): ...
class select(pairedtag): ...
class option(pairedtag): ...
class h1(pairedtag): ...
class h2(pairedtag): ...
class h3(pairedtag): ...
class h4(pairedtag): ...
class h5(pairedtag): ...
class h6(pairedtag): ...
class nav(pairedtag): ...
class footer(pairedtag): ...
class header(pairedtag): ...
class section(pairedtag): ...
class article(pairedtag): ...
class aside(pairedtag): ...
class dl(pairedtag): ...
class dt(pairedtag): ...
class dd(pairedtag): ...
class fieldset(pairedtag): ...
class legend(pairedtag): ...
class pre(pairedtag): ...
class code(pairedtag): ...
class blockquote(pairedtag): ...
class html(pairedtag): ...
class head(pairedtag): ...
class body(pairedtag): ...
class time(pairedtag): ...
class strong(pairedtag): ...
class small(pairedtag): ...
class template(pairedtag): ...
class li(pairedtag): ...
class ul(pairedtag): ...
class ol(ul): ...
